definitions:
  models.Country:
    properties:
      code:
        description: В доработке
        example: Russia
        type: string
      id:
        example: 141
        type: integer
      name:
        example: Russia
        type: string
    type: object
  models.ErrorJSON:
    properties:
      error:
        type: string
    type: object
  models.League:
    properties:
      id:
        example: 17201
        type: integer
      logo:
        example: https://tmssl.akamaized.net/images/logo/normal/ru1.png?lm=1582769594
        type: string
        x-nullable: true
      position:
        example: First Tier
        type: string
      title:
        example: Premier Liga
        type: string
      url:
        example: https://transfermarkt.com/premier-liga/startseite/wettbewerb/RU1
        type: string
    type: object
  models.Player:
    properties:
      id:
        example: 15570
        type: integer
      url:
        example: https://transfermarkt.com/igor-akinfeev/profil/spieler/15570
        type: string
    type: object
  models.PlayerDetail:
    properties:
      age:
        description: nullable
        example: 24
        type: integer
      birth_country:
        description: nullable
        example: 9
        type: integer
      birth_date:
        description: nullable
        example: Feb 10, 1996
        type: string
      contract_expires:
        description: nullable
        type: string
      contract_rental_expires:
        description: nullable
        type: string
      contracts:
        example:
        - http://www.instagram.com/emanuel_mammana24/
        items:
          type: string
        type: array
      country:
        description: nullable
        example: 9
        type: integer
      country_2:
        description: nullable
        example: 75
        type: integer
      current_club:
        description: nullable
        example: 964
        type: integer
      current_rental:
        description: nullable
        type: integer
      height:
        description: nullable
        example: 183
        type: integer
      image_url:
        example: https://tmssl.akamaized.net/images/portrait/header/275512-1572532565.png?lm=1572532580
        type: string
      name:
        example: Emanuel Mammana
        type: string
      position:
        description: nullable
        example: Defender - Centre-Back
        type: string
      shock_foot:
        description: nullable
        example: right
        type: string
      transfers:
        items:
          $ref: '#/definitions/models.Transfer'
        type: array
    type: object
  models.Season:
    properties:
      period:
        example: 2019
        type: integer
      season_end:
        example: 30-06-2020
        type: string
      season_start:
        example: 01-07-2019
        type: string
    type: object
  models.Team:
    properties:
      id:
        example: 2410
        type: integer
      players:
        items:
          $ref: '#/definitions/models.Player'
        type: array
      title:
        example: CSKA Moscow
        type: string
      url:
        example: https://transfermarkt.com/zska-moskau/startseite/verein/2410/saison_id/2019
        type: string
    type: object
  models.TeamDetail:
    properties:
      country:
        example: 141
        type: integer
      founded:
        description: nullable
        example: 22-02-2008
        type: string
      logo:
        description: nullable
        example: https://tmssl.akamaized.net/images/wappen/head/16704.png?lm=1499524238
        type: string
    type: object
  models.Transfer:
    properties:
      cost:
        description: nullable
        example: €2.00m
        type: string
      date:
        example: "2017-01-01T00:00:00Z"
        type: string
      fee:
        description: nullable
        example: €3.50m
        type: string
      from_team:
        description: nullable
        example: "28095"
        type: string
      season:
        type: string
      to_team:
        description: nullable
        example: "964"
        type: string
      transfer_type:
        description: 1 - арена, 0 - все остальное
        enum:
        - 0
        - 1
        example: 0
        type: integer
    type: object
info:
  contact: {}
  license: {}
paths:
  /countries:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Country'
            type: array
      summary: Список стран
  /leagues:
    get:
      parameters:
      - description: ID страны (напр. 141)
        in: query
        name: country
        required: true
        type: integer
      - description: Период сезона (напр. 2019)
        in: query
        name: season_period
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.League'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorJSON'
        "408": {}
      summary: Список лиг страны за определенный сезон
  /player_detail:
    get:
      parameters:
      - description: URL игрока
        in: query
        name: url
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.PlayerDetail'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorJSON'
        "408": {}
      summary: Карточка игрока
  /seasons:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Season'
            type: array
      summary: Список сезонов с 1900г. по текущий
  /team_compositions:
    get:
      parameters:
      - description: URL соревнования
        in: query
        name: league_url
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Team'
            type: array
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorJSON'
        "408": {}
      summary: Список команд и игроков в них по соревнованию (лига & сезон)
  /team_detail:
    get:
      parameters:
      - description: URL клуба
        in: query
        name: url
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.TeamDetail'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/models.ErrorJSON'
        "408": {}
      summary: Карточка клуба
swagger: "2.0"
